// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/1/2025, 9:40:27 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/plugins/**/*.{js,ts,mjs}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/composables/**/**/*.{js,ts,mjs}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/utils/**/**/*.{js,ts,mjs}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/composables/**/*.{js,ts,mjs}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/utils/**/*.{js,ts,mjs}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/viet_slide_and_advertising/viet_slide_and_advertising/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;